#!/usr/bin/env python3
"""
proposalgen.py — the proof block, and the proposal's shape, as data.

The Cockpit's proposal was coming back "draft, tokens missing" with fifteen
blanks in it: six [BUILD n CLIENT] / [BUILD n RESULT] pairs and three
[TESTIMONIAL] slots. The model was right to leave them empty — inventing a
client name in a document whose entire job is proving the work is real is the
one mistake that cannot be walked back.

So the facts live here now, taken verbatim from the Miami Family Law Group
proposal that shipped on Aug 1 2026 and settled at $2,950 — the calibration
point the whole pricing catalogue is anchored to. Nothing below is invented. If
a build or a quote is not in this file, it does not go in a proposal.

Emits cockpit-proof-block.js, which promptgen splices into the Prompt of Record
so the model is handed the real thing instead of a placeholder.

    python3 proposalgen.py
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "cockpit-proof-block.js")

# Verbatim from the shipped MFLG proposal, page 05, "Comparable builds".
# client type -> what was broken -> what shipped. Never a company name.
BUILDS = [
    ("Online Course Platform",
     "enrollment and course delivery lived on two disconnected platforms",
     "rebuilt as one connected system, cutting manual enrollment work to zero"),
    ("Financial Services Firm",
     "capital call notices were tracked and chased by hand across spreadsheets",
     "automated the notice cascade and the payment reconciliation end to end"),
    ("Cleaning Services Company",
     "operations were scattered and there was no system to start from",
     "a four milestone build brought them onto one connected system from a standing start"),
    ("Restoration Contractor",
     "reporting lived across scattered spreadsheets",
     "delivered one dashboard the office and the client could both trust"),
    ("Moving Company",
     "field crews worked off memory and phone calls",
     "shipped a mobile app that tracks every stage of a move as it happens"),
    ("Grocery Industry Association",
     "a marketing automation had gone stale inside a portal already running dozens of live workflows",
     "reconciled it against the working ones and relaunched it without breaking anything already in motion"),
]

TESTIMONIAL = {
    "quote": "The process was smooth and stress free from start to finish. I would call it a "
             "ten out of ten, and I am already planning to come back for the next project.",
    "name":  "Chelsea",
    "title": "Founder, 6 Months to Speech",
}

# Page 05, the four numbers across the top.
TRACK_RECORD = [
    ("50+",  "projects delivered"),
    ("100%", "client satisfaction"),
    ("5",    "weeks to go live"),
    ("14",   "days of support after handover"),
]

# The eight pages, in order, with what each one is FOR. This is the shape a
# Launch Forte proposal has; it is not a suggestion.
PAGES = [
    ("Cover", "reference, date, client name, the engagement title, and one sentence on what "
              "they end up with. Then prepared for, engagement type, delivery window, investment."),
    ("Situation", "where things stand in their own words and numbers. The path today drawn as "
                  "steps with ONE marked failure point, then what this is costing now, then what "
                  "changes. Name the break in a single bolded sentence."),
    ("Scope", "the deliverables, numbered 01 upward, each a heading and two or three plain "
              "sentences. The last two are always a live acceptance test and a handover."),
    ("Investment", "the derived figure, the milestone split, and a week by week schedule. Then "
                   "what is and is not included, changes and scope, revisions, payment."),
    ("Track record", "the four numbers, one testimonial, and the comparable builds below."),
    ("Operating terms", "how updates work, what to expect, keeping things moving, acceptance, "
                        "decision maker, support, cancellation and refunds."),
    ("Standard terms", "the thirteen numbered clauses, unchanged, version dated."),
    ("Acceptance", "what is needed to begin — access, information, kickoff — and the four step "
                   "approval: reply, invoice, fund and send access, the clock starts."),
]


def main():
    lines = []
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// THE PROOF BLOCK — generated by proposalgen.py. Do not hand edit.")
    lines.append("//")
    lines.append("// Fifteen blanks used to ship in every proposal: six build slots and three")
    lines.append("// testimonial slots, all empty, all marked 'tokens missing'. The model left")
    lines.append("// them empty because it had nothing true to put there, which was correct.")
    lines.append("// These are the real ones, from the proposal that shipped and settled.")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("const __PROOF = [''," )
    lines.append("  '=== THE TRACK RECORD. REAL, AND THE ONLY BUILDS THAT MAY BE NAMED ===',")
    lines.append("  'Never invent a client, a number or a quote. Never name a company.',")
    lines.append("  'If a build is not on this list it does not exist for this proposal.',")
    for a, b in TRACK_RECORD:
        lines.append("  '%s %s.'," % (a, b))
    lines.append("  '',")
    lines.append("  'COMPARABLE BUILDS, described by client TYPE only:',")
    for i, (who, broke, shipped) in enumerate(BUILDS, 1):
        lines.append("  '%d. %s — %s; %s.'," % (i, who, broke, shipped))
    lines.append("  '',")
    lines.append("  'THE ONE TESTIMONIAL ON FILE. Use it verbatim or not at all:',")
    lines.append("  '\"%s\"'," % TESTIMONIAL["quote"])
    lines.append("  '  — %s, %s',"  % (TESTIMONIAL["name"], TESTIMONIAL["title"]))
    lines.append("  '',")
    lines.append("  '=== THE SHAPE OF A LAUNCH FORTE PROPOSAL. EIGHT PAGES, THIS ORDER ===',")
    for i, (name, what) in enumerate(PAGES, 1):
        lines.append("  '%02d %s: %s'," % (i, name, what.replace("'", "\\'")))
    lines.append("  '',")
    lines.append("  'A PLACEHOLDER IN A PROPOSAL IS A DEFECT. If a fact is not above, cut the')")
    lines.append("  ;")
    body = "\n".join(lines)
    # keep it a single valid array literal
    body = body.replace("  'A PLACEHOLDER IN A PROPOSAL IS A DEFECT. If a fact is not above, cut the')\n  ;",
                        "  'A PLACEHOLDER IN A PROPOSAL IS A DEFECT. If a fact is not above, cut the',\n"
                        "  'line rather than leave a bracketed token in a document a client reads.',\n"
                        "].join('\\n');")
    body = body.replace("const __PROOF = ['',", "const __PROOF = [''," )
    open(OUT, "w").write(body + "\n")
    print("wrote %s: %d chars | %d builds | %d pages"
          % (os.path.basename(OUT), len(body), len(BUILDS), len(PAGES)))
    return 0


sys.exit(main())
